#!/usr/bin/env ruby
################################################################################
# Copyright 2008, Ruboss Technology Corporation.
#
# This software is dual-licensed under both the terms of the Ruboss Commercial
# License as published by Ruboss Technology Corporation and under the terms of
# the GNU General Public License v3 (GPL v3) as published by the Free Software
# Foundation.
#
# Your use of the software is governed by the terms specified in the
# LICENSE.txt file included with the source code. This file will either contain
# the Ruboss Commercial License or the GPL v3, depending on whether you
# are using the commercial version or the GPL v3 version of the software.
# To learn more or to buy a commercial license, please go to http://ruboss.com.
################################################################################
require File.dirname(__FILE__) + '/../config/boot'
require File.dirname(__FILE__) + '/../config/environment'
require 'rails_generator'
require 'rails_generator/scripts/generate'

source = 'db/model.txt'
File.open(source, 'r').each_line do |line|
  line.strip!
  puts 'running: rscaffold ' + line
  Rails::Generator::Scripts::Generate.new.run(["rscaffold"] + line.split, 
    :flex_only => ARGV.include?('flexonly')) unless line.empty? or line =~ /^#/
  puts 'done ...'
  sleep 1
end
Rails::Generator::Scripts::Generate.new.run(["rconfig"], :app_only => true, :skip_framework => ARGV.include?('skipframework'))
